server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200/"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: service-client
          uri: lb://service-client
          predicates:
            - Path=/clients/**
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/products/**
        - id: service-authentication
          uri: lb://service-authentication
          predicates:
            - Path=/login/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/